
 
const elements = [
    {
        "id": "h",
        "name": "Hydrogen",
        "symbol": "H",
        "atomicNumber": 1,
        "group": 1,
        "period": 1,
        "block": "s",
        "valency": "1",
        "atomicMass": "1.008 u",
        "neutrons": 0,
        "category": "Nonmetal",
        "electronConfiguration": "1s1",
        "phase": "Gas",
        "electronegativity": 2.2,
        "discoveredBy": "Henry Cavendish"
    },
    {
        "id": "he",
        "name": "Helium",
        "symbol": "He",
        "atomicNumber": 2,
        "group": 18,
        "period": 1,
        "block": "s",
        "valency": "0",
        "atomicMass": "4.0026 u",
        "neutrons": 2,
        "category": "Noble Gas",
        "electronConfiguration": "1s2",
        "phase": "Gas",
        "electronegativity": null,
        "discoveredBy": "Pierre Janssen, Norman Lockyer"
    },
    {
        "id": "li",
        "name": "Lithium",
        "symbol": "Li",
        "atomicNumber": 3,
        "group": 1,
        "period": 2,
        "block": "s",
        "valency": "1",
        "atomicMass": "6.94 u",
        "neutrons": 4,
        "category": "Alkali Metal",
        "electronConfiguration": "[He] 2s1",
        "phase": "Solid",
        "electronegativity": 0.98,
        "discoveredBy": "Johan Arfwedson"
    },
    {
        "id": "be",
        "name": "Beryllium",
        "symbol": "Be",
        "atomicNumber": 4,
        "group": 2,
        "period": 2,
        "block": "s",
        "valency": "2",
        "atomicMass": "9.0122 u",
        "neutrons": 5,
        "category": "Alkaline Earth Metal",
        "electronConfiguration": "[He] 2s2",
        "phase": "Solid",
        "electronegativity": 1.57,
        "discoveredBy": "Louis Nicolas Vauquelin"
    },
    {
        "id": "b",
        "name": "Boron",
        "symbol": "B",
        "atomicNumber": 5,
        "group": 13,
        "period": 2,
        "block": "p",
        "valency": "3",
        "atomicMass": "10.81 u",
        "neutrons": 6,
        "category": "Metalloid",
        "electronConfiguration": "[He] 2s2 2p1",
        "phase": "Solid",
        "electronegativity": 2.04,
        "discoveredBy": "Joseph Louis Gay-Lussac, Louis Jacques Thénard"
    },
    {
        "id": "c",
        "name": "Carbon",
        "symbol": "C",
        "atomicNumber": 6,
        "group": 14,
        "period": 2,
        "block": "p",
        "valency": "4",
        "atomicMass": "12.011 u",
        "neutrons": 6,
        "category": "Nonmetal",
        "electronConfiguration": "[He] 2s2 2p2",
        "phase": "Solid",
        "electronegativity": 2.55,
        "discoveredBy": "Unknown"
    },
    {
        "id": "n",
        "name": "Nitrogen",
        "symbol": "N",
        "atomicNumber": 7,
        "group": 15,
        "period": 2,
        "block": "p",
        "valency": "3",
        "atomicMass": "14.007 u",
        "neutrons": 7,
        "category": "Nonmetal",
        "electronConfiguration": "[He] 2s2 2p3",
        "phase": "Gas",
        "electronegativity": 3.04,
        "discoveredBy": "Daniel Rutherford"
    },
    {
        "id": "o",
        "name": "Oxygen",
        "symbol": "O",
        "atomicNumber": 8,
        "group": 16,
        "period": 2,
        "block": "p",
        "valency": "2",
        "atomicMass": "15.999 u",
        "neutrons": 8,
        "category": "Nonmetal",
        "electronConfiguration": "[He] 2s2 2p4",
        "phase": "Gas",
        "electronegativity": 3.44,
        "discoveredBy": "Carl Wilhelm Scheele, Joseph Priestley"
    },
    {
        "id": "f",
        "name": "Fluorine",
        "symbol": "F",
        "atomicNumber": 9,
        "group": 17,
        "period": 2,
        "block": "p",
        "valency": "1",
        "atomicMass": "18.998 u",
        "neutrons": 10,
        "category": "Halogen",
        "electronConfiguration": "[He] 2s2 2p5",
        "phase": "Gas",
        "electronegativity": 3.98,
        "discoveredBy": "Henri Moissan"
    },
    {
        "id": "ne",
        "name": "Neon",
        "symbol": "Ne",
        "atomicNumber": 10,
        "group": 18,
        "period": 2,
        "block": "p",
        "valency": "0",
        "atomicMass": "20.18 u",
        "neutrons": 10,
        "category": "Noble Gas",
        "electronConfiguration": "[He] 2s2 2p6",
        "phase": "Gas",
        "electronegativity": null,
        "discoveredBy": "Morris Travers, William Ramsay"
    },
    {
        "id": "na",
        "name": "Sodium",
        "symbol": "Na",
        "atomicNumber": 11,
        "group": 1,
        "period": 3,
        "block": "s",
        "valency": "1",
        "atomicMass": "22.98976928 u",
        "neutrons": 12,
        "category": "alkali metal",
        "electronConfiguration": "[Ne] 3s1",
        "phase": "solid",
        "electronegativity": 0.93,
        "discoveredBy": "Humphry Davy"
    },
    {
        "id": "mg",
        "name": "Magnesium",
        "symbol": "Mg",
        "atomicNumber": 12,
        "group": 2,
        "period": 3,
        "block": "s",
        "valency": "2",
        "atomicMass": "24.305 u",
        "neutrons": 12,
        "category": "alkaline earth metal",
        "electronConfiguration": "[Ne] 3s2",
        "phase": "solid",
        "electronegativity": 1.31,
        "discoveredBy": "Humphry Davy"
    },
    {
        "id": "al",
        "name": "Aluminium",
        "symbol": "Al",
        "atomicNumber": 13,
        "group": 13,
        "period": 3,
        "block": "p",
        "valency": "3",
        "atomicMass": "26.9815385 u",
        "neutrons": 14,
        "category": "post-transition metal",
        "electronConfiguration": "[Ne] 3s2 3p1",
        "phase": "solid",
        "electronegativity": 1.61,
        "discoveredBy": "Hans Ørsted"
    },
    {
        "id": "si",
        "name": "Silicon",
        "symbol": "Si",
        "atomicNumber": 14,
        "group": 14,
        "period": 3,
        "block": "p",
        "valency": "4",
        "atomicMass": "28.085 u",
        "neutrons": 14,
        "category": "metalloid",
        "electronConfiguration": "[Ne] 3s2 3p2",
        "phase": "solid",
        "electronegativity": 1.9,
        "discoveredBy": "Jöns Jacob Berzelius"
    },
    {
        "id": "p",
        "name": "Phosphorus",
        "symbol": "P",
        "atomicNumber": 15,
        "group": 15,
        "period": 3,
        "block": "p",
        "valency": "3",
        "atomicMass": "30.973761998 u",
        "neutrons": 16,
        "category": "nonmetal",
        "electronConfiguration": "[Ne] 3s2 3p3",
        "phase": "solid",
        "electronegativity": 2.19,
        "discoveredBy": "Hennig Brand"
    },
    {
        "id": "s",
        "name": "Sulfur",
        "symbol": "S",
        "atomicNumber": 16,
        "group": 16,
        "period": 3,
        "block": "p",
        "valency": "2",
        "atomicMass": "32.06 u",
        "neutrons": 16,
        "category": "nonmetal",
        "electronConfiguration": "[Ne] 3s2 3p4",
        "phase": "solid",
        "electronegativity": 2.58,
        "discoveredBy": "Unknown"
    },
    {
        "id": "cl",
        "name": "Chlorine",
        "symbol": "Cl",
        "atomicNumber": 17,
        "group": 17,
        "period": 3,
        "block": "p",
        "valency": "1",
        "atomicMass": "35.45 u",
        "neutrons": 18,
        "category": "halogen",
        "electronConfiguration": "[Ne] 3s2 3p5",
        "phase": "gas",
        "electronegativity": 3.16,
        "discoveredBy": "Carl Wilhelm Scheele"
    },
    {
        "id": "ar",
        "name": "Argon",
        "symbol": "Ar",
        "atomicNumber": 18,
        "group": 18,
        "period": 3,
        "block": "p",
        "valency": "0",
        "atomicMass": "39.948 u",
        "neutrons": 22,
        "category": "noble gas",
        "electronConfiguration": "[Ne] 3s2 3p6",
        "phase": "gas",
        "electronegativity": 0,
        "discoveredBy": "Lord Rayleigh & William Ramsay"
    },
    {
        "id": "k",
        "name": "Potassium",
        "symbol": "K",
        "atomicNumber": 19,
        "group": 1,
        "period": 4,
        "block": "s",
        "valency": "1",
        "atomicMass": "39.0983 u",
        "neutrons": 20,
        "category": "alkali metal",
        "electronConfiguration": "[Ar] 4s1",
        "phase": "solid",
        "electronegativity": 0.82,
        "discoveredBy": "Humphry Davy"
    },
    {
        "id": "ca",
        "name": "Calcium",
        "symbol": "Ca",
        "atomicNumber": 20,
        "group": 2,
        "period": 4,
        "block": "s",
        "valency": "2",
        "atomicMass": "40.078 u",
        "neutrons": 20,
        "category": "alkaline earth metal",
        "electronConfiguration": "[Ar] 4s2",
        "phase": "solid",
        "electronegativity": 1.0,
        "discoveredBy": "Humphry Davy"
    },
    {
        "id": "sc",
        "name": "Scandium",
        "symbol": "Sc",
        "atomicNumber": 21,
        "group": 3,
        "period": 4,
        "block": "d",
        "valency": "3",
        "atomicMass": "44.955908 u",
        "neutrons": 24,
        "category": "transition metal",
        "electronConfiguration": "[Ar] 3d1 4s2",
        "phase": "solid",
        "electronegativity": 1.36,
        "discoveredBy": "Lars Fredrik Nilson"
    },
    {
        "id": "ti",
        "name": "Titanium",
        "symbol": "Ti",
        "atomicNumber": 22,
        "group": 4,
        "period": 4,
        "block": "d",
        "valency": "4",
        "atomicMass": "47.867 u",
        "neutrons": 26,
        "category": "transition metal",
        "electronConfiguration": "[Ar] 3d2 4s2",
        "phase": "solid",
        "electronegativity": 1.54,
        "discoveredBy": "William Gregor"
    },
    {
        "id": "v",
        "name": "Vanadium",
        "symbol": "V",
        "atomicNumber": 23,
        "group": 5,
        "period": 4,
        "block": "d",
        "valency": "5",
        "atomicMass": "50.9415 u",
        "neutrons": 28,
        "category": "transition metal",
        "electronConfiguration": "[Ar] 3d3 4s2",
        "phase": "solid",
        "electronegativity": 1.63,
        "discoveredBy": "Andrés Manuel del Río"
    },
    {
        "id": "cr",
        "name": "Chromium",
        "symbol": "Cr",
        "atomicNumber": 24,
        "group": 6,
        "period": 4,
        "block": "d",
        "valency": "6",
        "atomicMass": "51.9961 u",
        "neutrons": 28,
        "category": "transition metal",
        "electronConfiguration": "[Ar] 3d5 4s1",
        "phase": "solid",
        "electronegativity": 1.66,
        "discoveredBy": "Louis Nicolas Vauquelin"
    },
    {
        "id": "mn",
        "name": "Manganese",
        "symbol": "Mn",
        "atomicNumber": 25,
        "group": 7,
        "period": 4,
        "block": "d",
        "valency": "7",
        "atomicMass": "54.938044 u",
        "neutrons": 30,
        "category": "transition metal",
        "electronConfiguration": "[Ar] 3d5 4s2",
        "phase": "solid",
        "electronegativity": 1.55,
        "discoveredBy": "Carl Wilhelm Scheele"
    },
    {
        "id": "fe",
        "name": "Iron",
        "symbol": "Fe",
        "atomicNumber": 26,
        "group": 8,
        "period": 4,
        "block": "d",
        "valency": "2",
        "atomicMass": "55.845 u",
        "neutrons": 30,
        "category": "transition metal",
        "electronConfiguration": "[Ar] 3d6 4s2",
        "phase": "solid",
        "electronegativity": 1.83,
        "discoveredBy": "Unknown"
    },
    {
        "id": "co",
        "name": "Cobalt",
        "symbol": "Co",
        "atomicNumber": 27,
        "group": 9,
        "period": 4,
        "block": "d",
        "valency": "2",
        "atomicMass": "58.933194 u",
        "neutrons": 32,
        "category": "transition metal",
        "electronConfiguration": "[Ar] 3d7 4s2",
        "phase": "solid",
        "electronegativity": 1.88,
        "discoveredBy": "Georg Brandt"
    },
    {
        "id": "ni",
        "name": "Nickel",
        "symbol": "Ni",
        "atomicNumber": 28,
        "group": 10,
        "period": 4,
        "block": "d",
        "valency": "2",
        "atomicMass": "58.6934 u",
        "neutrons": 31,
        "category": "transition metal",
        "electronConfiguration": "[Ar] 3d8 4s2",
        "phase": "solid",
        "electronegativity": 1.91,
        "discoveredBy": "Axel Fredrik Cronstedt"
    },
    {
        "id": "cu",
        "name": "Copper",
        "symbol": "Cu",
        "atomicNumber": 29,
        "group": 11,
        "period": 4,
        "block": "d",
        "valency": "2",
        "atomicMass": "63.546 u",
        "neutrons": 35,
        "category": "transition metal",
        "electronConfiguration": "[Ar] 3d10 4s1",
        "phase": "solid",
        "electronegativity": 1.9,
        "discoveredBy": "Unknown"
    },
    {
        "id": "zn",
        "name": "Zinc",
        "symbol": "Zn",
        "atomicNumber": 30,
        "group": 12,
        "period": 4,
        "block": "d",
        "valency": "2",
        "atomicMass": "65.38 u",
        "neutrons": 35,
        "category": "transition metal",
        "electronConfiguration": "[Ar] 3d10 4s2",
        "phase": "solid",
        "electronegativity": 1.65,
        "discoveredBy": "Andreas Marggraf"
    },
    {
        "id": "ga",
        "name": "Gallium",
        "symbol": "Ga",
        "atomicNumber": 31,
        "group": 13,
        "period": 4,
        "block": "p",
        "valency": "3",
        "atomicMass": "69.723 u",
        "neutrons": 39,
        "category": "post-transition metal",
        "electronConfiguration": "[Ar] 3d10 4s2 4p1",
        "phase": "solid",
        "electronegativity": 1.81,
        "discoveredBy": "Paul Émile Lecoq de Boisbaudran"
    },
    {
        "id": "ge",
        "name": "Germanium",
        "symbol": "Ge",
        "atomicNumber": 32,
        "group": 14,
        "period": 4,
        "block": "p",
        "valency": "4",
        "atomicMass": "72.63 u",
        "neutrons": 41,
        "category": "metalloid",
        "electronConfiguration": "[Ar] 3d10 4s2 4p2",
        "phase": "solid",
        "electronegativity": 2.01,
        "discoveredBy": "Clemens Winkler"
    },
    {
        "id": "as",
        "name": "Arsenic",
        "symbol": "As",
        "atomicNumber": 33,
        "group": 15,
        "period": 4,
        "block": "p",
        "valency": "3",
        "atomicMass": "74.921595 u",
        "neutrons": 42,
        "category": "metalloid",
        "electronConfiguration": "[Ar] 3d10 4s2 4p3",
        "phase": "solid",
        "electronegativity": 2.18,
        "discoveredBy": "Unknown"
    },
    {
        "id": "se",
        "name": "Selenium",
        "symbol": "Se",
        "atomicNumber": 34,
        "group": 16,
        "period": 4,
        "block": "p",
        "valency": "2",
        "atomicMass": "78.971 u",
        "neutrons": 45,
        "category": "nonmetal",
        "electronConfiguration": "[Ar] 3d10 4s2 4p4",
        "phase": "solid",
        "electronegativity": 2.55,
        "discoveredBy": "Jöns Jacob Berzelius"
    },
    {
        "id": "br",
        "name": "Bromine",
        "symbol": "Br",
        "atomicNumber": 35,
        "group": 17,
        "period": 4,
        "block": "p",
        "valency": "1",
        "atomicMass": "79.904 u",
        "neutrons": 45,
        "category": "halogen",
        "electronConfiguration": "[Ar] 3d10 4s2 4p5",
        "phase": "liquid",
        "electronegativity": 2.96,
        "discoveredBy": "Antoine Jérôme Balard"
    },
    {
        "id": "kr",
        "name": "Krypton",
        "symbol": "Kr",
        "atomicNumber": 36,
        "group": 18,
        "period": 4,
        "block": "p",
        "valency": "0",
        "atomicMass": "83.798 u",
        "neutrons": 48,
        "category": "noble gas",
        "electronConfiguration": "[Ar] 3d10 4s2 4p6",
        "phase": "gas",
        "electronegativity": 3.0,
        "discoveredBy": "William Ramsay & Morris Travers"
    },
    {
        "id": "rb",
        "name": "Rubidium",
        "symbol": "Rb",
        "atomicNumber": 37,
        "group": 1,
        "period": 5,
        "block": "s",
        "valency": "1",
        "atomicMass": "85.4678 u",
        "neutrons": 48,
        "category": "alkali metal",
        "electronConfiguration": "[Kr] 5s1",
        "phase": "solid",
        "electronegativity": 0.82,
        "discoveredBy": "Robert Bunsen & Gustav Kirchhoff"
    },
    {
        "id": "sr",
        "name": "Strontium",
        "symbol": "Sr",
        "atomicNumber": 38,
        "group": 2,
        "period": 5,
        "block": "s",
        "valency": "2",
        "atomicMass": "87.62 u",
        "neutrons": 50,
        "category": "alkaline earth metal",
        "electronConfiguration": "[Kr] 5s2",
        "phase": "solid",
        "electronegativity": 0.95,
        "discoveredBy": "Adair Crawford"
    },
    {
        "id": "y",
        "name": "Yttrium",
        "symbol": "Y",
        "atomicNumber": 39,
        "group": 3,
        "period": 5,
        "block": "d",
        "valency": "3",
        "atomicMass": "88.90584 u",
        "neutrons": 50,
        "category": "transition metal",
        "electronConfiguration": "[Kr] 4d1 5s2",
        "phase": "solid",
        "electronegativity": 1.22,
        "discoveredBy": "Johan Gadolin"
    },
    {
        "id": "zr",
        "name": "Zirconium",
        "symbol": "Zr",
        "atomicNumber": 40,
        "group": 4,
        "period": 5,
        "block": "d",
        "valency": "4",
        "atomicMass": "91.224 u",
        "neutrons": 51,
        "category": "transition metal",
        "electronConfiguration": "[Kr] 4d2 5s2",
        "phase": "solid",
        "electronegativity": 1.33,
        "discoveredBy": "Martin Heinrich Klaproth"
    },
    {
        "id": "nb",
        "name": "Niobium",
        "symbol": "Nb",
        "atomicNumber": 41,
        "group": 5,
        "period": 5,
        "block": "d",
        "valency": "5",
        "atomicMass": "92.906 u",
        "neutrons": 52,
        "category": "Transition Metal",
        "electronConfiguration": "[Kr] 4d4 5s1",
        "phase": "Solid",
        "electronegativity": 1.6,
        "discoveredBy": "Charles Hatchett"
    },
    {
        "id": "mo",
        "name": "Molybdenum",
        "symbol": "Mo",
        "atomicNumber": 42,
        "group": 6,
        "period": 5,
        "block": "d",
        "valency": "6",
        "atomicMass": "95.95 u",
        "neutrons": 54,
        "category": "Transition Metal",
        "electronConfiguration": "[Kr] 4d5 5s1",
        "phase": "Solid",
        "electronegativity": 2.16,
        "discoveredBy": "Carl Wilhelm Scheele"
    },
    {
        "id": "tc",
        "name": "Technetium",
        "symbol": "Tc",
        "atomicNumber": 43,
        "group": 7,
        "period": 5,
        "block": "d",
        "valency": "7",
        "atomicMass": "98 u",
        "neutrons": 55,
        "category": "Transition Metal",
        "electronConfiguration": "[Kr] 4d5 5s2",
        "phase": "Solid",
        "electronegativity": 1.9,
        "discoveredBy": "Emilio Segrè"
    },
    {
        "id": "ru",
        "name": "Ruthenium",
        "symbol": "Ru",
        "atomicNumber": 44,
        "group": 8,
        "period": 5,
        "block": "d",
        "valency": "8",
        "atomicMass": "101.07 u",
        "neutrons": 57,
        "category": "Transition Metal",
        "electronConfiguration": "[Kr] 4d7 5s1",
        "phase": "Solid",
        "electronegativity": 2.2,
        "discoveredBy": "Karl Ernst Claus"
    },
    {
        "id": "rh",
        "name": "Rhodium",
        "symbol": "Rh",
        "atomicNumber": 45,
        "group": 9,
        "period": 5,
        "block": "d",
        "valency": "3",
        "atomicMass": "102.91 u",
        "neutrons": 58,
        "category": "Transition Metal",
        "electronConfiguration": "[Kr] 4d8 5s1",
        "phase": "Solid",
        "electronegativity": 2.28,
        "discoveredBy": "William Hyde Wollaston"
    },
    {
        "id": "pd",
        "name": "Palladium",
        "symbol": "Pd",
        "atomicNumber": 46,
        "group": 10,
        "period": 5,
        "block": "d",
        "valency": "2",
        "atomicMass": "106.42 u",
        "neutrons": 60,
        "category": "Transition Metal",
        "electronConfiguration": "[Kr] 4d10",
        "phase": "Solid",
        "electronegativity": 2.2,
        "discoveredBy": "William Hyde Wollaston"
    },
    {
        "id": "ag",
        "name": "Silver",
        "symbol": "Ag",
        "atomicNumber": 47,
        "group": 11,
        "period": 5,
        "block": "d",
        "valency": "1",
        "atomicMass": "107.87 u",
        "neutrons": 61,
        "category": "Transition Metal",
        "electronConfiguration": "[Kr] 4d10 5s1",
        "phase": "Solid",
        "electronegativity": 1.93,
        "discoveredBy": "Unknown"
    },
    {
        "id": "cd",
        "name": "Cadmium",
        "symbol": "Cd",
        "atomicNumber": 48,
        "group": 12,
        "period": 5,
        "block": "d",
        "valency": "2",
        "atomicMass": "112.41 u",
        "neutrons": 64,
        "category": "Transition Metal",
        "electronConfiguration": "[Kr] 4d10 5s2",
        "phase": "Solid",
        "electronegativity": 1.69,
        "discoveredBy": "Karl Hermann"
    },
    {
        "id": "in",
        "name": "Indium",
        "symbol": "In",
        "atomicNumber": 49,
        "group": 13,
        "period": 5,
        "block": "p",
        "valency": "3",
        "atomicMass": "114.82 u",
        "neutrons": 66,
        "category": "Post-Transition Metal",
        "electronConfiguration": "[Kr] 4d10 5s2 5p1",
        "phase": "Solid",
        "electronegativity": 1.78,
        "discoveredBy": "Ferdinand Reich"
    },
    {
        "id": "sn",
        "name": "Tin",
        "symbol": "Sn",
        "atomicNumber": 50,
        "group": 14,
        "period": 5,
        "block": "p",
        "valency": "4",
        "atomicMass": "118.71 u",
        "neutrons": 69,
        "category": "Post-Transition Metal",
        "electronConfiguration": "[Kr] 4d10 5s2 5p2",
        "phase": "Solid",
        "electronegativity": 1.96,
        "discoveredBy": "Unknown"
    },
    {
        "id": "sb",
        "name": "Antimony",
        "symbol": "Sb",
        "atomicNumber": 51,
        "group": 15,
        "period": 5,
        "block": "p",
        "valency": "3",
        "atomicMass": "121.76 u",
        "neutrons": 71,
        "category": "Metalloid",
        "electronConfiguration": "[Kr] 4d10 5s2 5p3",
        "phase": "Solid",
        "electronegativity": 2.05,
        "discoveredBy": "Unknown"
    },
    {
        "id": "te",
        "name": "Tellurium",
        "symbol": "Te",
        "atomicNumber": 52,
        "group": 16,
        "period": 5,
        "block": "p",
        "valency": "2",
        "atomicMass": "127.6 u",
        "neutrons": 76,
        "category": "Metalloid",
        "electronConfiguration": "[Kr] 4d10 5s2 5p4",
        "phase": "Solid",
        "electronegativity": 2.1,
        "discoveredBy": "Franz Müller von Reichenstein"
    },
    {
        "id": "i",
        "name": "Iodine",
        "symbol": "I",
        "atomicNumber": 53,
        "group": 17,
        "period": 5,
        "block": "p",
        "valency": "1",
        "atomicMass": "126.9 u",
        "neutrons": 74,
        "category": "Halogen",
        "electronConfiguration": "[Kr] 4d10 5s2 5p5",
        "phase": "Solid",
        "electronegativity": 2.66,
        "discoveredBy": "Bernard Courtois"
    },
    {
        "id": "xe",
        "name": "Xenon",
        "symbol": "Xe",
        "atomicNumber": 54,
        "group": 18,
        "period": 5,
        "block": "p",
        "valency": "0",
        "atomicMass": "131.29 u",
        "neutrons": 77,
        "category": "Noble Gas",
        "electronConfiguration": "[Kr] 4d10 5s2 5p6",
        "phase": "Gas",
        "electronegativity": "--",
        "discoveredBy": "William Ramsay"
    },
    {
        "id": "cs",
        "name": "Cesium",
        "symbol": "Cs",
        "atomicNumber": 55,
        "group": 1,
        "period": 6,
        "block": "s",
        "valency": "1",
        "atomicMass": "132.91 u",
        "neutrons": 78,
        "category": "Alkali Metal",
        "electronConfiguration": "[Xe] 6s1",
        "phase": "Solid",
        "electronegativity": 0.79,
        "discoveredBy": "Robert Bunsen"
    },
    {
        "id": "ba",
        "name": "Barium",
        "symbol": "Ba",
        "atomicNumber": 56,
        "group": 2,
        "period": 6,
        "block": "s",
        "valency": "2",
        "atomicMass": "137.33 u",
        "neutrons": 81,
        "category": "Alkaline Earth Metal",
        "electronConfiguration": "[Xe] 6s2",
        "phase": "Solid",
        "electronegativity": 0.89,
        "discoveredBy": "Humphry Davy"
    },
    {
        "id": "la",
        "name": "Lanthanum",
        "symbol": "La",
        "atomicNumber": 57,
        "group": 3,
        "period": 6,
        "block": "d",
        "valency": "3",
        "atomicMass": "138.91 u",
        "neutrons": 82,
        "category": "Lanthanide",
        "electronConfiguration": "[Xe] 5d1 6s2",
        "phase": "Solid",
        "electronegativity": 1.1,
        "discoveredBy": "Carl Gustaf Mosander"
    },
    {
        "id": "ce",
        "name": "Cerium",
        "symbol": "Ce",
        "atomicNumber": 58,
        "group": 4,
        "period": 6,
        "block": "f",
        "valency": "4",
        "atomicMass": "140.12 u",
        "neutrons": 82,
        "category": "Lanthanide",
        "electronConfiguration": "[Xe] 4f1 5d1 6s2",
        "phase": "Solid",
        "electronegativity": 1.12,
        "discoveredBy": "Jöns Jakob Berzelius"
    },
    {
        "id": "pr",
        "name": "Praseodymium",
        "symbol": "Pr",
        "atomicNumber": 59,
        "group": 5,
        "period": 6,
        "block": "f",
        "valency": "3",
        "atomicMass": "140.91 u",
        "neutrons": 82,
        "category": "Lanthanide",
        "electronConfiguration": "[Xe] 4f3 6s2",
        "phase": "Solid",
        "electronegativity": 1.13,
        "discoveredBy": "Carl Auer von Welsbach"
    },
    {
        "id": "nd",
        "name": "Neodymium",
        "symbol": "Nd",
        "atomicNumber": 60,
        "group": 6,
        "period": 6,
        "block": "f",
        "valency": "3",
        "atomicMass": "144.24 u",
        "neutrons": 84,
        "category": "Lanthanide",
        "electronConfiguration": "[Xe] 4f4 6s2",
        "phase": "Solid",
        "electronegativity": 1.14,
        "discoveredBy": "Carl Auer von Welsbach"
    },
    {
        "id": "pm",
        "name": "Promethium",
        "symbol": "Pm",
        "atomicNumber": 61,
        "group": 7,
        "period": 6,
        "block": "f",
        "valency": "3",
        "atomicMass": "145 u",
        "neutrons": 84,
        "category": "Lanthanide",
        "electronConfiguration": "[Xe] 4f5 6s2",
        "phase": "Solid",
        "electronegativity": 1.13,
        "discoveredBy": "Jacob A. Marinsky"
    },
    {
        "id": "sm",
        "name": "Samarium",
        "symbol": "Sm",
        "atomicNumber": 62,
        "group": 8,
        "period": 6,
        "block": "f",
        "valency": "3",
        "atomicMass": "150.36 u",
        "neutrons": 88,
        "category": "Lanthanide",
        "electronConfiguration": "[Xe] 4f6 6s2",
        "phase": "Solid",
        "electronegativity": 1.17,
        "discoveredBy": "Paul Émile Lecoq de Boisbaudran"
    },
    {
        "id": "eu",
        "name": "Europium",
        "symbol": "Eu",
        "atomicNumber": 63,
        "group": 9,
        "period": 6,
        "block": "f",
        "valency": "2",
        "atomicMass": "151.96 u",
        "neutrons": 89,
        "category": "Lanthanide",
        "electronConfiguration": "[Xe] 4f7 6s2",
        "phase": "Solid",
        "electronegativity": 1.2,
        "discoveredBy": "Eugène-Anatole Demarçay"
    },
    {
        "id": "gd",
        "name": "Gadolinium",
        "symbol": "Gd",
        "atomicNumber": 64,
        "group": 10,
        "period": 6,
        "block": "f",
        "valency": "3",
        "atomicMass": "157.25 u",
        "neutrons": 93,
        "category": "Lanthanide",
        "electronConfiguration": "[Xe] 4f7 5d1 6s2",
        "phase": "Solid",
        "electronegativity": 1.2,
        "discoveredBy": "Jean Charles Galissard de Marignac"
    },
    {
        "id": "tb",
        "name": "Terbium",
        "symbol": "Tb",
        "atomicNumber": 65,
        "group": 11,
        "period": 6,
        "block": "f",
        "valency": "3",
        "atomicMass": "158.93 u",
        "neutrons": 94,
        "category": "Lanthanide",
        "electronConfiguration": "[Xe] 4f9 6s2",
        "phase": "Solid",
        "electronegativity": 1.2,
        "discoveredBy": "Carl Gustaf Mosander"
    },
    {
        "id": "dy",
        "name": "Dysprosium",
        "symbol": "Dy",
        "atomicNumber": 66,
        "group": 12,
        "period": 6,
        "block": "f",
        "valency": "3",
        "atomicMass": "162.5 u",
        "neutrons": 97,
        "category": "Lanthanide",
        "electronConfiguration": "[Xe] 4f10 6s2",
        "phase": "Solid",
        "electronegativity": 1.22,
        "discoveredBy": "Paul Émile Lecoq de Boisbaudran"
    },
    {
        "id": "ho",
        "name": "Holmium",
        "symbol": "Ho",
        "atomicNumber": 67,
        "group": 13,
        "period": 6,
        "block": "f",
        "valency": "3",
        "atomicMass": "164.93 u",
        "neutrons": 98,
        "category": "Lanthanide",
        "electronConfiguration": "[Xe] 4f11 6s2",
        "phase": "Solid",
        "electronegativity": 1.23,
        "discoveredBy": "Per Teodor Cleve"
    },
    {
        "id": "er",
        "name": "Erbium",
        "symbol": "Er",
        "atomicNumber": 68,
        "group": 14,
        "period": 6,
        "block": "f",
        "valency": "3",
        "atomicMass": "167.26 u",
        "neutrons": 99,
        "category": "Lanthanide",
        "electronConfiguration": "[Xe] 4f12 6s2",
        "phase": "Solid",
        "electronegativity": 1.24,
        "discoveredBy": "Carl Gustaf Mosander"
    },
    {
        "id": "tm",
        "name": "Thulium",
        "symbol": "Tm",
        "atomicNumber": 69,
        "group": 15,
        "period": 6,
        "block": "f",
        "valency": "3",
        "atomicMass": "168.93 u",
        "neutrons": 99,
        "category": "Lanthanide",
        "electronConfiguration": "[Xe] 4f13 6s2",
        "phase": "Solid",
        "electronegativity": 1.25,
        "discoveredBy": "Per Teodor Cleve"
    },
    {
        "id": "yb",
        "name": "Ytterbium",
        "symbol": "Yb",
        "atomicNumber": 70,
        "group": 16,
        "period": 6,
        "block": "f",
        "valency": "2",
        "atomicMass": "173.05 u",
        "neutrons": 103,
        "category": "Lanthanide",
        "electronConfiguration": "[Xe] 4f14 6s2",
        "phase": "Solid",
        "electronegativity": 1.1,
        "discoveredBy": "Jean Charles Galissard de Marignac"
    },
    {
        "id": "lu",
        "name": "Lutetium",
        "symbol": "Lu",
        "atomicNumber": 71,
        "group": 17,
        "period": 6,
        "block": "d",
        "valency": "3",
        "atomicMass": "174.97 u",
        "neutrons": 104,
        "category": "Lanthanide",
        "electronConfiguration": "[Xe] 4f14 5d1 6s2",
        "phase": "Solid",
        "electronegativity": 1.27,
        "discoveredBy": "Georges Urbain"
    },
    {
        "id": "hf",
        "name": "Hafnium",
        "symbol": "Hf",
        "atomicNumber": 72,
        "group": 4,
        "period": 6,
        "block": "d",
        "valency": "4",
        "atomicMass": "178.49 u",
        "neutrons": 106,
        "category": "Transition Metal",
        "electronConfiguration": "[Xe] 4f14 5d2 6s2",
        "phase": "Solid",
        "electronegativity": 1.3,
        "discoveredBy": "Dirk Coster"
    },
    {
        "id": "ta",
        "name": "Tantalum",
        "symbol": "Ta",
        "atomicNumber": 73,
        "group": 5,
        "period": 6,
        "block": "d",
        "valency": "5",
        "atomicMass": "180.95 u",
        "neutrons": 108,
        "category": "Transition Metal",
        "electronConfiguration": "[Xe] 4f14 5d3 6s2",
        "phase": "Solid",
        "electronegativity": 1.5,
        "discoveredBy": "Anders Gustaf Ekeberg"
    },
    {
        "id": "w",
        "name": "Tungsten",
        "symbol": "W",
        "atomicNumber": 74,
        "group": 6,
        "period": 6,
        "block": "d",
        "valency": "6",
        "atomicMass": "183.84 u",
        "neutrons": 110,
        "category": "Transition Metal",
        "electronConfiguration": "[Xe] 4f14 5d4 6s2",
        "phase": "Solid",
        "electronegativity": 2.36,
        "discoveredBy": "Fausto and Juan José Elhuyar"
    },
    {
        "id": "re",
        "name": "Rhenium",
        "symbol": "Re",
        "atomicNumber": 75,
        "group": 7,
        "period": 6,
        "block": "d",
        "valency": "7",
        "atomicMass": "186.21 u",
        "neutrons": 111,
        "category": "Transition Metal",
        "electronConfiguration": "[Xe] 4f14 5d5 6s2",
        "phase": "Solid",
        "electronegativity": 1.9,
        "discoveredBy": "Masataka Ogawa"
    },
    {
        "id": "os",
        "name": "Osmium",
        "symbol": "Os",
        "atomicNumber": 76,
        "group": 8,
        "period": 6,
        "block": "d",
        "valency": "8",
        "atomicMass": "190.23 u",
        "neutrons": 114,
        "category": "Transition Metal",
        "electronConfiguration": "[Xe] 4f14 5d6 6s2",
        "phase": "Solid",
        "electronegativity": 2.2,
        "discoveredBy": "Smithson Tennant"
    },
    {
        "id": "ir",
        "name": "Iridium",
        "symbol": "Ir",
        "atomicNumber": 77,
        "group": 9,
        "period": 6,
        "block": "d",
        "valency": "6",
        "atomicMass": "192.22 u",
        "neutrons": 115,
        "category": "Transition Metal",
        "electronConfiguration": "[Xe] 4f14 5d7 6s2",
        "phase": "Solid",
        "electronegativity": 2.2,
        "discoveredBy": "Smithson Tennant"
    },
    {
        "id": "pt",
        "name": "Platinum",
        "symbol": "Pt",
        "atomicNumber": 78,
        "group": 10,
        "period": 6,
        "block": "d",
        "valency": "6",
        "atomicMass": "195.08 u",
        "neutrons": 117,
        "category": "Transition Metal",
        "electronConfiguration": "[Xe] 4f14 5d9 6s1",
        "phase": "Solid",
        "electronegativity": 2.28,
        "discoveredBy": "Unknown"
    },
    {
        "id": "au",
        "name": "Gold",
        "symbol": "Au",
        "atomicNumber": 79,
        "group": 11,
        "period": 6,
        "block": "d",
        "valency": "3",
        "atomicMass": "196.97 u",
        "neutrons": 118,
        "category": "Transition Metal",
        "electronConfiguration": "[Xe] 4f14 5d10 6s1",
        "phase": "Solid",
        "electronegativity": 2.54,
        "discoveredBy": "Unknown"
    },
    {
        "id": "hg",
        "name": "Mercury",
        "symbol": "Hg",
        "atomicNumber": 80,
        "group": 12,
        "period": 6,
        "block": "d",
        "valency": "2",
        "atomicMass": "200.59 u",
        "neutrons": 121,
        "category": "Transition Metal",
        "electronConfiguration": "[Xe] 4f14 5d10 6s2",
        "phase": "Liquid",
        "electronegativity": 2.0,
        "discoveredBy": "Unknown"
    },
    {
        "id": "tl",
        "name": "Thallium",
        "symbol": "Tl",
        "atomicNumber": 81,
        "group": 13,
        "period": 6,
        "block": "p",
        "valency": "3",
        "atomicMass": "204.38 u",
        "neutrons": 123,
        "category": "Post-transition metal",
        "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p1",
        "phase": "Solid",
        "electronegativity": 1.62,
        "discoveredBy": "William Crookes"
    },
    {
        "id": "pb",
        "name": "Lead",
        "symbol": "Pb",
        "atomicNumber": 82,
        "group": 14,
        "period": 6,
        "block": "p",
        "valency": "4",
        "atomicMass": "207.2 u",
        "neutrons": 125,
        "category": "Post-transition metal",
        "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p2",
        "phase": "Solid",
        "electronegativity": 2.33,
        "discoveredBy": "Prehistoric"
    },
    {
        "id": "bi",
        "name": "Bismuth",
        "symbol": "Bi",
        "atomicNumber": 83,
        "group": 15,
        "period": 6,
        "block": "p",
        "valency": "3",
        "atomicMass": "208.98 u",
        "neutrons": 126,
        "category": "Post-transition metal",
        "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p3",
        "phase": "Solid",
        "electronegativity": 2.02,
        "discoveredBy": "Claude Geoffroy the Younger"
    },
    {
        "id": "po",
        "name": "Polonium",
        "symbol": "Po",
        "atomicNumber": 84,
        "group": 16,
        "period": 6,
        "block": "p",
        "valency": "2",
        "atomicMass": "209 u",
        "neutrons": 125,
        "category": "Metalloid",
        "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p4",
        "phase": "Solid",
        "electronegativity": 2.0,
        "discoveredBy": "Marie Curie"
    },
    {
        "id": "at",
        "name": "Astatine",
        "symbol": "At",
        "atomicNumber": 85,
        "group": 17,
        "period": 6,
        "block": "p",
        "valency": "1",
        "atomicMass": "210 u",
        "neutrons": 125,
        "category": "Halogen",
        "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p5",
        "phase": "Solid",
        "electronegativity": 2.2,
        "discoveredBy": "Dale R. Corson"
    },
    {
        "id": "rn",
        "name": "Radon",
        "symbol": "Rn",
        "atomicNumber": 86,
        "group": 18,
        "period": 6,
        "block": "p",
        "valency": "0",
        "atomicMass": "222 u",
        "neutrons": 136,
        "category": "Noble gas",
        "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p6",
        "phase": "Gas",
        "electronegativity": "Unknown",
        "discoveredBy": "Friedrich Dorn"
    },
    {
        "id": "fr",
        "name": "Francium",
        "symbol": "Fr",
        "atomicNumber": 87,
        "group": 1,
        "period": 7,
        "block": "s",
        "valency": "1",
        "atomicMass": "223 u",
        "neutrons": 136,
        "category": "Alkali metal",
        "electronConfiguration": "[Rn] 7s1",
        "phase": "Solid",
        "electronegativity": 0.7,
        "discoveredBy": "Marguerite Perey"
    },
    {
        "id": "ra",
        "name": "Radium",
        "symbol": "Ra",
        "atomicNumber": 88,
        "group": 2,
        "period": 7,
        "block": "s",
        "valency": "2",
        "atomicMass": "226 u",
        "neutrons": 138,
        "category": "Alkaline earth metal",
        "electronConfiguration": "[Rn] 7s2",
        "phase": "Solid",
        "electronegativity": 0.9,
        "discoveredBy": "Marie and Pierre Curie"
    },
    {
        "id": "ac",
        "name": "Actinium",
        "symbol": "Ac",
        "atomicNumber": 89,
        "group": 3,
        "period": 7,
        "block": "f",
        "valency": "3",
        "atomicMass": "227 u",
        "neutrons": 138,
        "category": "Actinide",
        "electronConfiguration": "[Rn] 6d1 7s2",
        "phase": "Solid",
        "electronegativity": 1.1,
        "discoveredBy": "André Debierne"
    },
    {
        "id": "th",
        "name": "Thorium",
        "symbol": "Th",
        "atomicNumber": 90,
        "group": 4,
        "period": 7,
        "block": "f",
        "valency": "4",
        "atomicMass": "232.04 u",
        "neutrons": 142,
        "category": "Actinide",
        "electronConfiguration": "[Rn] 6d2 7s2",
        "phase": "Solid",
        "electronegativity": 1.3,
        "discoveredBy": "Jöns Jakob Berzelius"
    },
    {
        "id": "pa",
        "name": "Protactinium",
        "symbol": "Pa",
        "atomicNumber": 91,
        "group": 5,
        "period": 7,
        "block": "f",
        "valency": "5",
        "atomicMass": "231.04 u",
        "neutrons": 140,
        "category": "Actinide",
        "electronConfiguration": "[Rn] 5f2 6d1 7s2",
        "phase": "Solid",
        "electronegativity": 1.5,
        "discoveredBy": "Oswald Helmuth Göhring, Kasimir Fajans"
    },
    {
        "id": "u",
        "name": "Uranium",
        "symbol": "U",
        "atomicNumber": 92,
        "group": 6,
        "period": 7,
        "block": "f",
        "valency": "6",
        "atomicMass": "238.03 u",
        "neutrons": 146,
        "category": "Actinide",
        "electronConfiguration": "[Rn] 5f3 6d1 7s2",
        "phase": "Solid",
        "electronegativity": 1.38,
        "discoveredBy": "Martin Heinrich Klaproth"
    },
    {
        "id": "np",
        "name": "Neptunium",
        "symbol": "Np",
        "atomicNumber": 93,
        "group": 7,
        "period": 7,
        "block": "f",
        "valency": "7",
        "atomicMass": "237 u",
        "neutrons": 144,
        "category": "Actinide",
        "electronConfiguration": "[Rn] 5f4 6d1 7s2",
        "phase": "Solid",
        "electronegativity": 1.36,
        "discoveredBy": "Edwin McMillan, Philip Abelson"
    },
    {
        "id": "pu",
        "name": "Plutonium",
        "symbol": "Pu",
        "atomicNumber": 94,
        "group": 8,
        "period": 7,
        "block": "f",
        "valency": "6",
        "atomicMass": "244 u",
        "neutrons": 150,
        "category": "Actinide",
        "electronConfiguration": "[Rn] 5f6 7s2",
        "phase": "Solid",
        "electronegativity": 1.28,
        "discoveredBy": "Glenn T. Seaborg"
    },
    {
        "id": "am",
        "name": "Americium",
        "symbol": "Am",
        "atomicNumber": 95,
        "group": 9,
        "period": 7,
        "block": "f",
        "valency": "3",
        "atomicMass": "243 u",
        "neutrons": 148,
        "category": "Actinide",
        "electronConfiguration": "[Rn] 5f7 7s2",
        "phase": "Solid",
        "electronegativity": 1.3,
        "discoveredBy": "Glenn T. Seaborg"
    },
    {
        "id": "cm",
        "name": "Curium",
        "symbol": "Cm",
        "atomicNumber": 96,
        "group": 10,
        "period": 7,
        "block": "f",
        "valency": "3",
        "atomicMass": "247 u",
        "neutrons": 151,
        "category": "Actinide",
        "electronConfiguration": "[Rn] 5f7 6d1 7s2",
        "phase": "Solid",
        "electronegativity": 1.3,
        "discoveredBy": "Glenn T. Seaborg"
    },
    {
        "id": "bk",
        "name": "Berkelium",
        "symbol": "Bk",
        "atomicNumber": 97,
        "group": 11,
        "period": 7,
        "block": "f",
        "valency": "3",
        "atomicMass": "247 u",
        "neutrons": 150,
        "category": "Actinide",
        "electronConfiguration": "[Rn] 5f9 7s2",
        "phase": "Solid",
        "electronegativity": 1.3,
        "discoveredBy": "Glenn T. Seaborg"
    },
    {
        "id": "cf",
        "name": "Californium",
        "symbol": "Cf",
        "atomicNumber": 98,
        "group": 12,
        "period": 7,
        "block": "f",
        "valency": "3",
        "atomicMass": "251 u",
        "neutrons": 153,
        "category": "Actinide",
        "electronConfiguration": "[Rn] 5f10 7s2",
        "phase": "Solid",
        "electronegativity": 1.3,
        "discoveredBy": "Stanley Thompson, Glenn Seaborg"
    },
    {
        "id": "es",
        "name": "Einsteinium",
        "symbol": "Es",
        "atomicNumber": 99,
        "group": 13,
        "period": 7,
        "block": "f",
        "valency": "3",
        "atomicMass": "252 u",
        "neutrons": 153,
        "category": "Actinide",
        "electronConfiguration": "[Rn] 5f11 7s2",
        "phase": "Solid",
        "electronegativity": 1.3,
        "discoveredBy": "Albert Ghiorso"
    },
    {
        "id": "fm",
        "name": "Fermium",
        "symbol": "Fm",
        "atomicNumber": 100,
        "group": 14,
        "period": 7,
        "block": "f",
        "valency": "3",
        "atomicMass": "257 u",
        "neutrons": 157,
        "category": "Actinide",
        "electronConfiguration": "[Rn] 5f12 7s2",
        "phase": "Solid",
        "electronegativity": 1.3,
        "discoveredBy": "Albert Ghiorso"
    },
    {
        "id": "md",
        "name": "Mendelevium",
        "symbol": "Md",
        "atomicNumber": 101,
        "group": 15,
        "period": 7,
        "block": "f",
        "valency": "3",
        "atomicMass": "258 u",
        "neutrons": 157,
        "category": "Actinide",
        "electronConfiguration": "[Rn] 5f13 7s2",
        "phase": "Solid",
        "electronegativity": 1.3,
        "discoveredBy": "Albert Ghiorso"
    },
    {
        "id": "no",
        "name": "Nobelium",
        "symbol": "No",
        "atomicNumber": 102,
        "group": 16,
        "period": 7,
        "block": "f",
        "valency": "2",
        "atomicMass": "259 u",
        "neutrons": 157,
        "category": "Actinide",
        "electronConfiguration": "[Rn] 5f14 7s2",
        "phase": "Solid",
        "electronegativity": 1.3,
        "discoveredBy": "Albert Ghiorso"
    },
    {
        "id": "lr",
        "name": "Lawrencium",
        "symbol": "Lr",
        "atomicNumber": 103,
        "group": 17,
        "period": 7,
        "block": "d",
        "valency": "3",
        "atomicMass": "266 u",
        "neutrons": 163,
        "category": "Actinide",
        "electronConfiguration": "[Rn] 5f14 7s2 7p1",
        "phase": "Solid",
        "electronegativity": 1.3,
        "discoveredBy": "Albert Ghiorso"
    },
    {
        "id": "rf",
        "name": "Rutherfordium",
        "symbol": "Rf",
        "atomicNumber": 104,
        "group": 4,
        "period": 7,
        "block": "d",
        "valency": "4",
        "atomicMass": "267 u",
        "neutrons": 163,
        "category": "Transition metal",
        "electronConfiguration": "[Rn] 5f14 6d2 7s2",
        "phase": "Solid",
        "electronegativity": 1.3,
        "discoveredBy": "Albert Ghiorso"
    },
    {
        "id": "db",
        "name": "Dubnium",
        "symbol": "Db",
        "atomicNumber": 105,
        "group": 5,
        "period": 7,
        "block": "d",
        "valency": "5",
        "atomicMass": "270 u",
        "neutrons": 165,
        "category": "Transition metal",
        "electronConfiguration": "[Rn] 5f14 6d3 7s2",
        "phase": "Solid",
        "electronegativity": 1.3,
        "discoveredBy": "Joint Institute for Nuclear Research"
    },
    {
        "id": "sg",
        "name": "Seaborgium",
        "symbol": "Sg",
        "atomicNumber": 106,
        "group": 6,
        "period": 7,
        "block": "d",
        "valency": "6",
        "atomicMass": "271 u",
        "neutrons": 165,
        "category": "Transition metal",
        "electronConfiguration": "[Rn] 5f14 6d4 7s2",
        "phase": "Solid",
        "electronegativity": 1.3,
        "discoveredBy": "Albert Ghiorso"
    },
    {
        "id": "bh",
        "name": "Bohrium",
        "symbol": "Bh",
        "atomicNumber": 107,
        "group": 7,
        "period": 7,
        "block": "d",
        "valency": "7",
        "atomicMass": "270 u",
        "neutrons": 163,
        "category": "Transition metal",
        "electronConfiguration": "[Rn] 5f14 6d5 7s2",
        "phase": "Solid",
        "electronegativity": 1.3,
        "discoveredBy": "Peter Armbruster, Gottfried Münzenberg"
    },
    {
        "id": "hs",
        "name": "Hassium",
        "symbol": "Hs",
        "atomicNumber": 108,
        "group": 8,
        "period": 7,
        "block": "d",
        "valency": "8",
        "atomicMass": "277 u",
        "neutrons": 169,
        "category": "Transition metal",
        "electronConfiguration": "[Rn] 5f14 6d6 7s2",
        "phase": "Solid",
        "electronegativity": 1.3,
        "discoveredBy": "Peter Armbruster, Gottfried Münzenberg"
    },
    {
        "id": "mt",
        "name": "Meitnerium",
        "symbol": "Mt",
        "atomicNumber": 109,
        "group": 9,
        "period": 7,
        "block": "d",
        "valency": "9",
        "atomicMass": "278 u",
        "neutrons": 169,
        "category": "Transition metal",
        "electronConfiguration": "[Rn] 5f14 6d7 7s2",
        "phase": "Solid",
        "electronegativity": 1.3,
        "discoveredBy": "Gesellschaft für Schwerionenforschung"
    },
    {
        "id": "ds",
        "name": "Darmstadtium",
        "symbol": "Ds",
        "atomicNumber": 110,
        "group": 10,
        "period": 7,
        "block": "d",
        "valency": "0",
        "atomicMass": "281 u",
        "neutrons": 77,
        "category": "Transition Metal",
        "electronConfiguration": "[Rn] 5f14 6d8 7s2",
        "phase": "Solid (predicted)",
        "electronegativity": "--",
        "discoveredBy": "GSI Helmholtz Centre"
    },
    {
        "id": "rg",
        "name": "Roentgenium",
        "symbol": "Rg",
        "atomicNumber": 111,
        "group": 11,
        "period": 7,
        "block": "d",
        "valency": "0",
        "atomicMass": "282 u",
        "neutrons": 77,
        "category": "Transition Metal",
        "electronConfiguration": "[Rn] 5f14 6d9 7s2",
        "phase": "Solid (predicted)",
        "electronegativity": "--",
        "discoveredBy": "GSI Helmholtz Centre"
    },
    {
        "id": "cn",
        "name": "Copernicium",
        "symbol": "Cn",
        "atomicNumber": 112,
        "group": 12,
        "period": 7,
        "block": "d",
        "valency": "0",
        "atomicMass": "285 u",
        "neutrons": 77,
        "category": "Transition Metal",
        "electronConfiguration": "[Rn] 5f14 6d10 7s2",
        "phase": "Gas (predicted)",
        "electronegativity": "--",
        "discoveredBy": "GSI Helmholtz Centre"
    },
    {
        "id": "nh",
        "name": "Nihonium",
        "symbol": "Nh",
        "atomicNumber": 113,
        "group": 13,
        "period": 7,
        "block": "p",
        "valency": "0",
        "atomicMass": "286 u",
        "neutrons": 77,
        "category": "Post-Transition Metal",
        "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p1",
        "phase": "Solid (predicted)",
        "electronegativity": "--",
        "discoveredBy": "RIKEN, Japan"
    },
    {
        "id": "fl",
        "name": "Flerovium",
        "symbol": "Fl",
        "atomicNumber": 114,
        "group": 14,
        "period": 7,
        "block": "p",
        "valency": "0",
        "atomicMass": "289 u",
        "neutrons": 77,
        "category": "Post-Transition Metal",
        "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p2",
        "phase": "Solid (predicted)",
        "electronegativity": "--",
        "discoveredBy": "Joint Institute for Nuclear Research"
    },
    {
        "id": "mc",
        "name": "Moscovium",
        "symbol": "Mc",
        "atomicNumber": 115,
        "group": 15,
        "period": 7,
        "block": "p",
        "valency": "0",
        "atomicMass": "290 u",
        "neutrons": 77,
        "category": "Post-Transition Metal",
        "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p3",
        "phase": "Solid (predicted)",
        "electronegativity": "--",
        "discoveredBy": "Joint Institute for Nuclear Research"
    },
    {
        "id": "lv",
        "name": "Livermorium",
        "symbol": "Lv",
        "atomicNumber": 116,
        "group": 16,
        "period": 7,
        "block": "p",
        "valency": "0",
        "atomicMass": "293 u",
        "neutrons": 77,
        "category": "Post-Transition Metal",
        "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p4",
        "phase": "Solid (predicted)",
        "electronegativity": "--",
        "discoveredBy": "Joint Institute for Nuclear Research"
    },
    {
        "id": "ts",
        "name": "Tennessine",
        "symbol": "Ts",
        "atomicNumber": 117,
        "group": 17,
        "period": 7,
        "block": "p",
        "valency": "0",
        "atomicMass": "294 u",
        "neutrons": 77,
        "category": "Halogen",
        "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p5",
        "phase": "Solid (predicted)",
        "electronegativity": "--",
        "discoveredBy": "Joint Institute for Nuclear Research"
    },
    {
        "id": "og",
        "name": "Oganesson",
        "symbol": "Og",
        "atomicNumber": 118,
        "group": 18,
        "period": 7,
        "block": "p",
        "valency": "0",
        "atomicMass": "294 u",
        "neutrons": 77,
        "category": "Noble Gas",
        "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p6",
        "phase": "Gas (predicted)",
        "electronegativity": "--",
        "discoveredBy": "Joint Institute for Nuclear Research"
    },
    {
        "id": "uue",
        "name": "Ununennium",
        "symbol": "Uue",
        "atomicNumber": 119,
        "group": 1,
        "period": 8,
        "block": "s",
        "valency": "1",
        "atomicMass": "315 u",
        "neutrons": 196,
        "category": "Alkali Metal",
        "electronConfiguration": "[Og] 8s1",
        "phase": "Solid (predicted)",
        "electronegativity": "--",
        "discoveredBy": "Predicted"
    },
    {
        "id": "ubn",
        "name": "Unbinilium",
        "symbol": "Ubn",
        "atomicNumber": 120,
        "group": 2,
        "period": 8,
        "block": "s",
        "valency": "2",
        "atomicMass": "320 u",
        "neutrons": 200,
        "category": "Alkaline Earth Metal",
        "electronConfiguration": "[Og] 8s2",
        "phase": "Solid (predicted)",
        "electronegativity": "--",
        "discoveredBy": "Predicted"
    }
]

// Most of the data above is AI generated and can contain inaccuracies

const nav = document.getElementById("nav");
const container = document.getElementById("elements");

for (const element of elements) {

    nav.innerHTML += `<a href="#${element.id}">${element.symbol}</a>\n`;

container.innerHTML += `
<div class="element-card" id="${element.id}">
    <div class="element-header">
        <div class="element-symbol">${element.symbol}</div>
        <div class="element-number">#${element.atomicNumber}</div>
    </div>

    <div class="element-name">${element.name}</div>

    <div class="element-info">
        <strong>Group</strong><span>${element.group ?? "-"}</span>
        <strong>Period</strong><span>${element.period}</span>
        <strong>Block</strong><span>${element.block}</span>
        <strong>Valency</strong><span>${element.valency}</span>
        <strong>Atomic Mass</strong><span>${element.atomicMass}</span>
        <strong>Neutrons</strong><span>${element.neutrons}</span>
    </div>
    <hr>
    <details>
        <summary>More Information</summary>
        <div class="element-info">
            <strong>Category</strong><span>${element.category}</span>
            <strong>Electron Configuration</strong><span>${element.electronConfiguration}</span>
            <strong>Phase</strong><span>${element.phase}</span>
            <strong>Electronegativity</strong><span>${element.electronegativity ?? "-"}</span>
            <strong>Discovered By</strong><span>${element.discoveredBy}</span>
        </div>
    </details>
</div>
`;
}

nav.addEventListener("click", (e) => {
    if (!e.target.matches("a")) return;
    e.preventDefault();

    const id = e.target.getAttribute("href").slice(1);
    const card = document.getElementById(id);

    card.scrollIntoView({
        behavior: "smooth",
        block: "center"
    });

    card.classList.remove("highlight-card");
    void card.offsetWidth;
    card.classList.add("highlight-card");
});



function scrollToTop(){
window.scrollTo({
  top: 0,
  left: 0,
  behavior: 'smooth'
});


}